[package]
name = "shitty_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shitty_types = { path = "../shitty_types" }

[dev-dependencies]
maplit = "1.0.2"
